//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosGAP.Model.Model
{
    using SegurosGAP.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSegurosGAPEntities : DbContext
    {
        public DBSegurosGAPEntities()
            : base("name=DBSegurosGAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PolizasSeguro> PolizasSeguros { get; set; }
        public virtual DbSet<TiposCubrimiento> TiposCubrimientoes { get; set; }
        public virtual DbSet<TiposRiesgo> TiposRiesgoes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<PolizasCliente> PolizasClientes { get; set; }
    }
}
