//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosGAP.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Application
    {
        [DataMember]public int IdApplication { get; set; }
        [DataMember]public string CodeApplication { get; set; }
        [DataMember]public string Name { get; set; }
        [DataMember]public int RefreshTokenLifeTime { get; set; }
        [DataMember]public string AllowedOrigin { get; set; }
        [DataMember]public bool Active { get; set; }
    }
}
